import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { HighlightActiveNavigation } from '../lib/highlightActiveNavigation'





// components:
import Layout from '../Components/Layout'
import HomePageContent from '../Components/Contents/HomePageContent'





export default function Home() {
















  return (
<Layout>
      <Head>

    {/* for google search console: */}
      <meta name="google-site-verification" content="-U70Yo_PUyJNjtc9GuyqT4vWVG0UDMjNYE247B5sORY" />

{/* SEO for Bing: */}
      <meta name="msvalidate.01" content="BB1EB7899B59F1CA72D84F367E74DB96" />


        <title>Lucy de Rojas - Web Development and Graphic Design</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

<HomePageContent />


</Layout>






  )
}
