import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'







// components:
import Layout from '../Components/Layout'
import HomePageContent from '../Components/Contents/HomePageContent'





export default function Home() {
  return (
<Layout>
      <Head>

    {/* for google search console: */}
      <meta name="google-site-verification" content="-U70Yo_PUyJNjtc9GuyqT4vWVG0UDMjNYE247B5sORY" />
        
        
        <title>Lucy de Rojas - Web Dev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

<HomePageContent />


</Layout>






  )
}
