import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'







// components:
import Layout from '../Components/Layout'






export default function Home() {
  return (
<Layout>
      <Head>
        <title>Lucy de Rojas - Web Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/DonQuiDesigns-logo.ico" />
      </Head>


<h1>home</h1>
<hr />

</Layout>






  )
}
